### ISSUE TITLE
Feature Request: original name detection / transparency bug

### ISSUE THREAD

**Issue by amanxy** [ForkandBeard/Alferd-Spritesheet-Unpacker#11]
first this tool is great to unpack sprite sheet it helped me a lot of times however it's going to save me a lot of times if it can rename image with its original names that in the plist file like this example. what i mean if only can read plist file along with the png sprite files and extract image with its original name.
As this example of plist coordinate of one image

 < key>image name xxx< /key>
            < dict>
                < key>frame< /key>
                < string>{{181, 1142}, {509, 171}}< /string >
                < key>offset</key >
                < string>{-2, 77}< /string >
                < key>rotated< /key >
                < string>false</string >
                < key>sourceColorRect< /key >
                < string>{{59, 153}, {509, 171}}< /string >
                < key>sourceSize< /key >
                < string>{630, 631}< /string >
            < /dict >

ASU should export the image as "image name xxx.png" and not as a number 01.png

Also there image pieces that should be exported as one single image as for ASU treat it as multiple images that why is so important if ASU can read plist coordinates {{181, 1142}, {509, 171}} its going to solve this problem even there is the ability to combine selection.

Also the software its doesnt have smart detection of transparency as sometimes it doesn't detect some images and remove pieces of images that share the same color as the background of sprite sheet imported even the sprite sheet have transparent background when imported to ASU the background become black and if there is black image inside the sprite sheet it won't be detected at all the same thing happened with transparent image that is inside the sprite sheet it will be exported with different color or it won't be exported at all.

**Comment by ForkandBeard** [comment]
I think if a user had a meta file with that level of detail they probably wouldn't need ASU, so I don't think I'm going to go down that route I'm afraid, happy obviously for someone else to take that on.

For your other issues please click the 'Options' button and try increasing the 'Distance between frames' value and untick 'Make background transparent'.

Hope that helps.
