### ISSUE TITLE
"Combine Selected" won't work well

### ISSUE THREAD

**Issue by brianRocha** [ForkandBeard/Alferd-Spritesheet-Unpacker#4]
That function appear to work when you use it,but when you try to export the combined sprites,the program just export the sprite that you tried to combine,not the sprite that was created after you combine It,even the program show It when you select all the sprites to export. (See the attached image below)
![screenshot_1](https://cloud.githubusercontent.com/assets/13719823/9155835/84399522-3e9c-11e5-9ff2-c2f5c3271545.png)

I don't know if It's my fault or something,but I can't make It work properly,even combining all the small frames in one,and combining them to the main sprite won't work..

**Comment by ForkandBeard** [comment]
Thanks for reporting this bug.

It's now fixed in version 14:
https://github.com/ForkandBeard/Alferd-Spritesheet-Unpacker/releases/tag/v14
