### ISSUE TITLE
ExportedOptionsMakeBackgroundTransparent=false ignored in 15'th release (tag/v15)

### ISSUE THREAD

**Issue by Deepscorn** [ForkandBeard/Alferd-Spritesheet-Unpacker#5]
Input: spritesheet with transparent background.
I've set:
```xml
<add key="ExportedOptionsMakeBackgroundTransparent" value="false"/>
```
in ASU.exe.config as I've done in versions 13 and 14.
* I've got: black background added to each exported image.
* I've expected: background will remain transparent

**Comment by ForkandBeard** [comment]
Thanks greatly for raising this issue (and using the app).

New version (v16) should hopefully fix this one.

**Comment by Deepscorn** [comment]
Thank you!
